version: '3.1'

services:
  codrr_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: level_up_backend_db
      MYSQL_ROOT_USER: matiscava
      MYSQL_USER: matiscava
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    